services:
  backend:
    build: ./backend
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8003:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "83:80"
    volumes:
      - ./backend/media:/var/www/media:ro
    depends_on:
      - "backend"
    restart: unless-stopped
